#!/bin/bash
set -e

# Pi-hole First-Time Setup Script
# Documented and persistent configuration for Pi-hole v6

# Auto-detect external IP
# We want the IP associated with the default route
DETECTED_IP=$(ip route get 8.8.8.8 | grep -oP 'src \K\S+')

if [ -f .env ]; then
    # Update PIHOLE_HOST_IP in .env if it differs or doesn't exist
    if grep -q "PIHOLE_HOST_IP=" .env; then
        sed -i "s/^PIHOLE_HOST_IP=.*/PIHOLE_HOST_IP=$DETECTED_IP/" .env
    else
        echo "PIHOLE_HOST_IP=$DETECTED_IP" >> .env
    fi
    
    echo "Configured PIHOLE_HOST_IP to $DETECTED_IP in .env"

    # Source environment variables
    export $(grep -v '^#' .env | xargs)
else
    echo "ERROR: .env file not found. Copy .env.example to .env and configure it."
    exit 1
fi

echo "--- Configuring Pi-hole Directories ---"
mkdir -p etc-pihole etc-dnsmasq.d

echo "--- Configuring Reverse DNS (Conditional Forwarding) ---"
# This ensures local hostnames are resolved by the router
sudo tee etc-dnsmasq.d/02-custom.conf <<EOF > /dev/null
# Custom dnsmasq settings for Pi-hole
# Managed by Antigravity - Optimized for v6 Hostnames

# Allow all origins (v6 handle this via FTLCONF, but dnsmasq layer safe-keep)
all-servers

# Local Network Settings
domain=lan
expand-hosts

# Conditional Forwarding (Router: $ROUTER_IP, Network: $LOCAL_NETWORK)
server=/lan/$ROUTER_IP
server=/$REV_SERVER_DOMAIN/$ROUTER_IP
EOF

echo "--- Configuring VPN DNS Forwarding ---"
if [ -n "$VPN_DNS_SERVER" ] && [ -n "$VPN_DOMAINS" ]; then
    echo "Configuring VPN DNS forwarding to $VPN_DNS_SERVER for: $VPN_DOMAINS"
    {
        echo "# Forward VPN domains to VPN DNS server"
        echo "# Generated by setup.sh - domains resolve via VPN network"
        echo "# Note: When VPN is down, queries will return SERVFAIL (no fallback)"
        IFS=',' read -ra DOMAINS <<< "$VPN_DOMAINS"
        for domain in "${DOMAINS[@]}"; do
            domain=$(echo "$domain" | xargs)  # trim whitespace
            echo "server=/$domain/$VPN_DNS_SERVER"
        done
    } | sudo tee etc-dnsmasq.d/03-vpn-forwarding.conf > /dev/null
else
    echo "VPN DNS forwarding not configured (VPN_DNS_SERVER not set)"
    # Remove old config if it exists and VPN is now disabled
    [ -f etc-dnsmasq.d/03-vpn-forwarding.conf ] && sudo rm etc-dnsmasq.d/03-vpn-forwarding.conf
fi

echo "--- Configuring Admin Credentials ---"
# The admin password is primarily driven by FTLCONF_webserver_api_password in docker-compose.yml.
# We ensure the directories are ready for FTL to write its persistent state.
if [ ! -f etc-pihole/pihole.toml ]; then
    echo "[setup] Initializing minimal pihole.toml..."
    sudo tee etc-pihole/pihole.toml <<EOF > /dev/null
[dns]
upstreams = ["8.8.8.8", "8.8.4.4"]
domain.name = "lan"
listeningMode = "all"
bogusPriv = false
domainNeeded = true

[misc]
etc_dnsmasq_d = true

[webserver]
api.password = "$ADMIN_PASSWORD"
EOF
fi

echo "--- Setup Complete ---"
echo "You can now run 'make update' to apply the configuration and start Pi-hole."
